print("Assalamuallaikum Wr. Wb")
print ("=================================================")
print ("Sebelumnya mohon ijin, disini saya akan memperkenalkan diri kepada")
print ("teman-teman semuanya. Perkenalkan nama saya IMAM SOLEHUDIN, orang-orang ") 
print ("sering memanggilnya imam. Nomor Induk Mahasiswa saya yaitu (312110290),")
print ("saya merupakan mahasiswa Prodi Teknik Informatika Universitas Pelita Bangsa.")
print ("Saya lahir di Ciamis dan sekarang saya sudah berumur 21 tahun. Saya sekarang ")
print ("tinggal di bekasi lebih tepatnya di kecamatan cikarang barat. Jika ada keperluan")
print ("pribadi atau ingin bermain ke rumah saya bisa hubungi saya pada nomor telepon")
print ("ini 087860815548. Terima Kasih.")
print ("=================================================")
print ("Waalaikumsalam Wr. Wb")
